App\Products\Domain\Entity\Product:
    collectionOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ['product:collection:get']
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ['product:item:get']
        put:
            method: 'PUT'
        patch:
            method: 'PATCH'
        post:
            method: 'POST'
