api_platform:
    title: '%env(API_PLATFORM_TITLE)%'
    description: '%env(API_PLATFORM_DESCRIPTION)%'
    version: '%env(API_PLATFORM_VERSION)%'
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
