framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing: ~
        # Comenta o elimina esta línea:
        # 'Symfony\Component\Scheduler\Transport\TaskMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'